### ISSUE TITLE
Will build, gives nested exception when used

### ISSUE THREAD

**Issue by JamesH1978** [robertogallea/jaas_relational_login#7]
Good afternoon,

I have a need to change one of the Java files, DBLogin.jar, as I believe it is adding strings that are already present in the returned SQL.
I am trying to remove the line ` String upwd2 = "$2a" + upwd.substring(3);` as my returned password hash already has the hash identifier  prepended and it always returns "Invalid password"

so therefore I need to build this from source to test my theory unfortunately whenever I try and build it the resulting jar file gives a nested exception:

```org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: org/springframework/security/crypto/password/PasswordEncoder
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1086)
Caused by: java.lang.NoClassDefFoundError: org/springframework/security/crypto/password/PasswordEncoder
        at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
Caused by: java.lang.ClassNotFoundException: org.springframework.security.crypto.password.PasswordEncoder
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)```

I have tried this with and without the line removal, so i must be not using the right syntax, i am just runnng `ant` in the root of the cloned repo. Could you perhaps tell me how this should be built? Java is not my language

Thanks
James

**Comment by JamesH1978** [comment]
for clarification, `$2y$10$..jXtIfO/ui6GR8N9OOjzO0ZM10PKxyJU1mhRUaUOs4SoK.XArU92` is exactly what is in my password field in the database and 
`$2y$10$..jXtIfO/ui6GR8N9OOjzO0ZM10PKxyJU1mhRUaUOs4SoK.XArU92` is exactly what the traced SQL query from the IDp returns, hence why my thinking that line is what is causing my issues.

Thanks again

James

**Comment by robertogallea** [comment]
Hi James,
I guess you're missing some dependencies. Indeed the exception dump tells that the class `org.springframework.security.crypto.password.PasswordEncoder` cannot be loaded. Thus, it seems that you didn't have the Spring Security Crypto component on your classpath. 

Honestly, I don't remember the details since I worked on this some years ago, and Java is not my main language too. However, you can try downloading this component and the jar to your runtime classpath.

Please let me know if you solve the issue.

**Comment by JamesH1978** [comment]
Thanks for the reply!

I realise time has passed since you worked on this project :)

it seems weird though that using your compiled jar it all works fine no exceptions. But as soon as a chine build the jar from the source it throws up that exception, no matter if I build the code with no changes all with the change I want to make.

I will see if I can do some more digging.

Thanks James

**Comment by robertogallea** [comment]
I think that the missing classes have been packaged in the jar. I can't
check that right now, but perhaps you can check it yourself.

Il mer 25 gen 2023, 11:54 JamesH1978 ***@***.***> ha scritto:

**Comment by JamesH1978** [comment]
hmmm ok, i think i just need to add the dependency to ivy.xml

Will give it a go

Thanks again

**Comment by JamesH1978** [comment]
```<ivy-module version="2.0">
    <info organisation="org.apache" module="JAAS_relational_login"/>
    <dependencies>
        <!-- https://mvnrepository.com/artifact/org.springframework.security/spring-security-crypto -->
        <dependency org="org.springframework.security" name="spring-security-crypto" rev="5.1.3.RELEASE"/>
        <!-- https://mvnrepository.com/artifact/commons-codec/commons-codec -->
        <dependency org="commons-codec" name="commons-codec" rev="1.10"/>
    </dependencies>
</ivy-module>``` spring-security-crypto already seems to be a dependency. unless I have to add passwordencoder implicity

**Comment by JamesH1978** [comment]
![image](https://user-images.githubusercontent.com/87171443/214562058-867b0675-48bb-4540-8fd4-7c2de77ba374.png)
already an implicit import in DBLogin.java, i must be building it wrong

**Comment by JamesH1978** [comment]
I am really confused now! I decided to open up the jar that you have posted on your website, and the class files in it are not the same as the ones in github, they do not reference the PasswordEncoder at all or bcrypt, they seem to be from an older version, but the error i get seems to pointing to line 71 of the DBLogin file, which correlates with the newer file on github. I am rebuilding and restarting jetty on every try, so i know i am not just retrying the same file, as i can consistenly go from a newly compiled one that throws the nested expection to the the precompiled on that works but doesnt authenticate our bcrypt passwords. Any more insight into this?

Thanks
James

**Comment by JamesH1978** [comment]
All sorted, had to build it in maven, so it gave me extra dependency jar files.

Seems to work well so far.

Thanks
James

**Comment by robertogallea** [comment]
That's good news. Hope the package is helpful for you.

If it is ok for you, please close the issue.
